export const TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  AUTH_ERROR: "AUTH_ERROR",
  ERRORS: "ERRORS",
  GET_PRODUCT: "GET_PRODUCT",
  PRODUCTS: "PRODUCTS",
  SUCCESSFUL_REGISTER: "SUCCESSFUL_REGISTER",
  FAILURE_REGISTER: "FAILURE_REGISTER",
};
